use std::{fs, io::Write, path::PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut files: Vec<(usize, String)> = Vec::new();

    for entry in fs::read_dir("src/days")? {
        let path = entry?.path();

        if path.extension().and_then(|x| x.to_str()) == Some("rs") {
            let name = path.file_stem().unwrap().to_str().unwrap().to_string();

            if let Some(num_str) = name.strip_prefix("day") {
                if let Ok(num) = num_str.parse::<usize>() {
                    files.push((num, name));
                }
            }
        }
    }

    files.sort_by_key(|(num, _)| *num);

    let out_path = PathBuf::from("src/days.rs");
    let mut out = fs::File::create(out_path)?;
    writeln!(out, "// Autogenerated, do not touch!")?;
    writeln!(out, "pub use crate::*;")?;

    for (_, name) in &files {
        writeln!(out, "pub mod {};", name)?;
    }

    writeln!(out)?;
    writeln!(
        out,
        "pub fn select_day(day: usize) -> Option<Box<dyn Solution>> {{"
    )?;
    writeln!(out, "    match day {{")?;

    for (num, name) in &files {
        writeln!(
            out,
            "        {} => Some(Box::new(crate::days::{}::Problem)),",
            num, name
        )?;
    }

    writeln!(out, "        _ => None,")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;

    Ok(())
}
