use std::{fs, io::Write, path::PathBuf};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut files: Vec<(usize, String)> = Vec::new();

    for entry in fs::read_dir("src/days")? {
        let path = entry?.path();

        if path.extension().and_then(|x| x.to_str()) == Some("rs") {
            let name = path.file_stem().unwrap().to_str().unwrap().to_string();

            if let Some(num_str) = name.strip_prefix("day") {
                if let Ok(num) = num_str.parse::<usize>() {
                    files.push((num, name));
                }
            }
        }
    }

    files.sort_by_key(|(num, _)| *num);

    let out_path = PathBuf::from("src/days.rs");
    let mut out = fs::File::create(out_path)?;
    writeln!(out, "// Autogenerated, do not touch!")?;
    writeln!(out, "pub use crate::*;")?;

    for (_, name) in &files {
        writeln!(out, "pub mod {};", name)?;
    }

    writeln!(out)?;
    writeln!(
        out,
        "pub fn select_day(day: usize) -> Option<Box<dyn Solution>> {{"
    )?;
    writeln!(out, "    match day {{")?;

    for (num, name) in &files {
        writeln!(
            out,
            "        {} => Some(Box::new(crate::days::{}::Problem)),",
            num, name
        )?;
    }

    writeln!(out, "        _ => None,")?;
    writeln!(out, "    }}")?;
    writeln!(out, "}}")?;

    fs::create_dir_all("benches")?;

    for (num, name) in &files {
        let bench_path = PathBuf::from(format!("benches/{}_bench.rs", name));
        let mut bench_file = fs::File::create(bench_path)?;

        writeln!(bench_file, "// Auto-generated by build.rs")?;
        writeln!(
            bench_file,
            "use criterion::{{criterion_group, criterion_main, Criterion}};"
        )?;
        writeln!(bench_file, "use aoc2025::Solution;")?;
        writeln!(bench_file, "use aoc2025::days::{}::Problem;", name)?;
        writeln!(bench_file)?;
        writeln!(
            bench_file,
            "const TEST_INPUT: &str = include_str!(\"../inputs/{:02}/test-input.txt\");",
            num
        )?;
        writeln!(
            bench_file,
            "const INPUT: &str = include_str!(\"../inputs/{:02}/input.txt\");",
            num
        )?;
        writeln!(bench_file)?;

        writeln!(bench_file, "fn bench_part1_test(c: &mut Criterion) {{")?;
        writeln!(bench_file, "    c.bench_function(\"{}_part1_test\", |b| b.iter(|| Problem.part_one(TEST_INPUT).unwrap()));", name)?;
        writeln!(bench_file, "}}")?;

        writeln!(bench_file, "fn bench_part2_test(c: &mut Criterion) {{")?;
        writeln!(bench_file, "    c.bench_function(\"{}_part2_test\", |b| b.iter(|| Problem.part_two(TEST_INPUT).unwrap()));", name)?;
        writeln!(bench_file, "}}")?;

        writeln!(bench_file, "fn bench_part1_real(c: &mut Criterion) {{")?;
        writeln!(
            bench_file,
            "    c.bench_function(\"{}_part1\", |b| b.iter(|| Problem.part_one(INPUT).unwrap()));",
            name
        )?;
        writeln!(bench_file, "}}")?;

        writeln!(bench_file, "fn bench_part2_real(c: &mut Criterion) {{")?;
        writeln!(
            bench_file,
            "    c.bench_function(\"{}_part2\", |b| b.iter(|| Problem.part_two(INPUT).unwrap()));",
            name
        )?;
        writeln!(bench_file, "}}")?;

        writeln!(
            bench_file,
            "criterion_group!(benches, bench_part1_test, bench_part2_test, bench_part1_real, bench_part2_real);"
        )?;
        writeln!(bench_file, "criterion_main!(benches);")?;
    }

    Ok(())
}
