// Autogenerated, do not touch!
pub use crate::*;
pub mod day01;
pub mod day02;

pub fn select_day(day: usize) -> Option<Box<dyn Solution>> {
    match day {
        1 => Some(Box::new(crate::days::day01::Problem)),
        2 => Some(Box::new(crate::days::day02::Problem)),
        _ => None,
    }
}
