on: 
  push:
    paths:
      - "2022/**"
    
name: CI (2022)
jobs:
  execute:
    name: Run application
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - uses: Swatinem/rust-cache@v2

    - name: Move to folder & run
      run: |
        cd 2022
        cargo build --release --quiet
        cargo run --release

  hyperfine:
    name: Bench
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v2

    - name: Install nightly toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - uses: Swatinem/rust-cache@v2

    - name: Install hyperfine
      run: |
        cargo install hyperfine --quiet

    - name: Move to folder & run
      run: |
        cd 2022
        cargo build --release --quiet
        hyperfine --warmup 3 -N './target/release/aoc2022'

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          args: --manifest-path 2022/Cargo.toml
          command: test