on: [push, pull_request]
name: Clippy (new version test, don't use it!)
jobs:
  clippy_check_ng:
    defaults:
      run:
        working-directory: ./2022
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy@master